### ISSUE TITLE
Plugin Reporting Errors

### ISSUE THREAD

**Issue by sektov** [WesleyLuk90/ffxiv-vr#14]
### Description ###

**Hello, sorry to bother you.**

 1. I followed the process in the README to start the plugin, but it encountered an error and provided the following log.
 2. I can see the game’s UI and input keys, but the screen is black, and SteamVR remains in a waiting state.
 3. I am using SteamVR. I've tried the troubleshooting methods mentioned, but they were still ineffective.
 4. I did not make the change mentioned in the error log regarding resizing the window.

### Error Details ###

[16:16][Info] Starting VR
[16:16][Error] Unexpected window size, expected 2704x2704 but got 576x960
[16:16][Error] If you resized the window, please restart VR
[16:16][Error] Error: Field not found: 'FFXIVClientStructs.FFXIV.Client.UI.UIInputData.CursorInputs'.
   at FfxivVR.Renderer.RenderCursor(ID3D11DeviceContext* context, Vector2D`1 windowSize)
   at FfxivVR.Renderer.RenderUITexture(ID3D11DeviceContext* context, Int32 width, Int32 height) in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\vr\Renderer.cs:line 232
   at FfxivVR.Renderer.RenderEye(ID3D11DeviceContext* context, FrameState frameState, View[] views, Eye eye, HandData hands) in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\vr\Renderer.cs:line 147
   at FfxivVR.VRSession.PrePresent(ID3D11DeviceContext* context) in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\VRSession.cs:line 183
   at FfxivVR.VRLifecycle.PrePresent() in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\VRLifecycle.cs:line 130
   at FfxivVR.GameHooks.<>c__DisplayClass16_0.<DXGIPresentDetour>b__0() in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\game\GameHooks.cs:line 111
   at FfxivVR.ExceptionHandler.FaultBarrier(Action block) in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\debug\ExceptionHandler.cs:line 19
[16:16][Error] Error: Failed to WaitSwapchainImage got result ErrorCallOrderInvalid
   at FfxivVR.Extensions.CheckResult(Result result, String action) in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\vr\Extensions.cs:line 12
   at FfxivVR.Renderer.RenderEye(ID3D11DeviceContext* context, FrameState frameState, View[] views, Eye eye, HandData hands) in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\vr\Renderer.cs:line 96
   at FfxivVR.VRSession.PrePresent(ID3D11DeviceContext* context) in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\VRSession.cs:line 183
   at FfxivVR.VRLifecycle.PrePresent() in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\VRLifecycle.cs:line 130
   at FfxivVR.GameHooks.<>c__DisplayClass16_0.<DXGIPresentDetour>b__0() in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\game\GameHooks.cs:line 111
   at FfxivVR.ExceptionHandler.FaultBarrier(Action block) in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\debug\ExceptionHandler.cs:line 19
[16:16][Error] Error: Failed to WaitSwapchainImage got result ErrorCallOrderInvalid
   at FfxivVR.Extensions.CheckResult(Result result, String action) in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\vr\Extensions.cs:line 12
   at FfxivVR.Renderer.RenderEye(ID3D11DeviceContext* context, FrameState frameState, View[] views, Eye eye, HandData hands) in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\vr\Renderer.cs:line 96
   at FfxivVR.VRSession.PrePresent(ID3D11DeviceContext* context) in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\VRSession.cs:line 183
   at FfxivVR.VRLifecycle.PrePresent() in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\VRLifecycle.cs:line 130
   at FfxivVR.GameHooks.<>c__DisplayClass16_0.<DXGIPresentDetour>b__0() in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\game\GameHooks.cs:line 111
   at FfxivVR.ExceptionHandler.FaultBarrier(Action block) in D:\a\ffxiv-vr\ffxiv-vr\FfxivVr\debug\ExceptionHandler.cs:line 19
[16:17][Info] Stopping VR

### Plugin version ###

 v0.0.31

**Comment by WesleyLuk90** [comment]
Based on those errors it seems like your game and dalamud/FFXIVClientStructs are on a different version. Can you make sure they are up to date?

**Comment by sektov** [comment]
> Based on those errors it seems like your game and dalamud/FFXIVClientStructs are on a different version. Can you make sure they are up to date?

Thank you for your attention to this matter.

I am currently using this plugin on the CN server, along with an adapted version of Dalamud. Previously, this plugin has always worked normally.

This is my Dalamud version and game version
![123](https://github.com/user-attachments/assets/61ef16f7-a3c1-482c-ae86-0d9d9d979f9a)
![12](https://github.com/user-attachments/assets/217f531d-79e4-490c-a89e-6bf8980a82b0)

**Comment by sektov** [comment]
> Based on those errors it seems like your game and dalamud/FFXIVClientStructs are on a different version. Can you make sure they are up to date?

Thank you for your attention to this matter. 
Your suggestion is absolutely correct.
I am currently using this plugin on the CN server, along with an adapted version of Dalamud.
the Dalamud I am using does not support api11, which resulted in this situation.
It was my negligence, sorry!
